<a href="https://colab.research.google.com/github/Khushi-Kumari947/NLP/blob/main/Text_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [7]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


# Bag of words


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [6]:
bow=cv.fit_transform(df['text'])

In [7]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [8]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [9]:
print(bow[1].toarray())

[[2 0 0 1 0]]


In [11]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

# N-grams

In [18]:
# In bag of words hyper parameter value n-grams is set
#(x,y)->x till y-1 combo like 1 gram 2 gram ... y-1 grams

In [14]:
cv1=CountVectorizer(ngram_range=(1,2))

In [15]:
bow=cv1.fit_transform(df['text'])

In [17]:
print(cv1.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


# Tf-Idf

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [9]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [10]:
print(tfidf.get_feature_names_out())

['campusx' 'comment' 'people' 'watch' 'write']
